# configs/models/dplm.yaml
defaults:
  - _self_

name: dplm

params: {}

init:
  _target_: replm.models.dplm.backend.DPLMInitConfig
  model_name: airkingbd/dplm_650m # you can also try airkingbd/dplm_150m
  torch_autocast: true

generation:
  _target_: replm.models.dplm.backend.DPLMGenerationConfig
  max_iter: 500
  sampling_strategy: gumbel_argmax # ['vanilla', 'argmax', 'gumbel_argmax']
  temperature: 1.0 # sweep: [0.7, 1.0, 1.3]
  disable_resample: false # sweep: [false, true]
  resample_ratio: 0.25 # sweep: [0.1, 0.15, 0.2, 0.25]

backend:
  task_type: mlm
  device: ${runtime.device}
  dtype: null
  default_pooling: mean
