defaults:
  - _self_

name: progen2_base # 27 layers

params:
  model_name: hugohrban/progen2-base
  prompt_text: "<|endoftext|>"
  length_offset: 1
  tokenizer_kwargs:
    trust_remote_code: true
  model_kwargs:
    trust_remote_code: true
    torch_dtype: auto
  generation_kwargs:
    do_sample: true
    eos_token_id: 0

backend:
  task_type: causal
  device: ${runtime.device}
  dtype: null
  default_pooling: last_nonpad
