defaults:
  - backend@backend: causal
  - _self_

name: progen2_small

params:
  model_name: hugohrban/progen2-small
  prompt_text: "<|endoftext|>"
  length_offset: 1
  tokenizer_kwargs:
    trust_remote_code: true
  model_kwargs:
    trust_remote_code: true
    torch_dtype: auto
  generation_kwargs:
    do_sample: true
    eos_token_id: 0
