defaults:
  - _self_

name: protgpt2 # 36 layers
params:
  model_name: nferruz/ProtGPT2
  prompt_text: "<|endoftext|>"
  residues_per_token: 4.0
  tokenizer_kwargs: {}
  model_kwargs: {}
  generation_kwargs:
    do_sample: true
    eos_token_id: 0

backend:
  task_type: causal
  device: ${runtime.device}
  dtype: null
  default_pooling: last_nonpad