# Balanced decoding preset tracking upstream defaults.
_target_: replm.config.ESM3GenerationConfig
track: sequence
invalid_ids: []
schedule: cosine
strategy: random
num_steps: 20
temperature: 1.0
temperature_annealing: true
top_p: 1.0
condition_on_coordinates_only: true
only_compute_backbone_rmsd: false
