defaults:
  - dataset: posneg
  - models: progen2_base
  - methods: contrastive_layer
  - _self_

exp:
  id: demo

io:
  root: outputs # {output_dir}
  save_activations: false # {save_activations}

runtime:
  seed: 42 # {seed}
  device: cpu # {device}

split:
  train: 10 # {train}
  test: 10 # {test}

activation:
    batch_size: 1 # {batch_size}
  
steering:
  layer: 0 # {layer} which layer you want to steer, works for method: contrastive_layer , probe_layer
  

generation:
  uncond:
    n: 1 # {uncond_n}
    length_min: 50 # {uncond_length_min}
    length_max: 512 # {uncond_length_max}
    overrides: {}
  prefix:
    n: 1 # {prefix_n}
    prefix_frac: 0.1 # 10% of the source sequence
    overrides: {}
